#include "Ball.h"
#include "FractionStruct.h"
#include "Monster.h"
#include "TriadStruct.h"
#include "animalLegNums.h"
#include "arrayLoop.h"
#include "binarySearch.h"
#include "bubbleSort.h"
#include "calculateAdRevenue.h"
#include "ch17ArraysPt1.h"
#include "dynamicAllocation.h"
#include "enumIndex.h"
#include "funcPointerCalculator.h"
#include "lambda.h"
#include "operatorOverloads.h"
#include "perfectSquares.h"
#include "quiz16.h"
#include "rangeBased.h"
#include "recurse.h"
#include "roscoes.h"
#include "stdVectorExample.h"
#include "vectorStack.h"

#include "..\common\common.h"

#include <iostream>
